const tarotCards = {
  majorArcana: [
    { name: "The Fool", meaning: "New beginnings, innocence, spontaneity, free spirit" },
    { name: "The Magician", meaning: "Manifestation, resourcefulness, power, inspired action" },
    { name: "The High Priestess", meaning: "Intuition, spiritual insight, divine feminine, the subconscious mind" },
    { name: "The Empress", meaning: "Femininity, beauty, nature, abundance" },
    { name: "The Emperor", meaning: "Authority, establishment, structure, control, fatherhood" },
    { name: "The Hierophant", meaning: "Spiritual wisdom, religious beliefs, conformity, tradition" },
    { name: "The Lovers", meaning: "Love, harmony, relationships, values alignment, choices" },
    { name: "The Chariot", meaning: "Control, willpower, success, determination, direction" },
    { name: "Strength", meaning: "Strength, courage, patience, control, compassion" },
    { name: "The Hermit", meaning: "Soul searching, introspection, inner guidance, solitude" },
    { name: "Wheel of Fortune", meaning: "Good luck, karma, life cycles, destiny, turning point" },
    { name: "Justice", meaning: "Justice, fairness, truth, cause and effect, law" },
    { name: "The Hanged Man", meaning: "Suspension, restriction, letting go, sacrifice" },
    { name: "Death", meaning: "Endings, beginnings, change, transformation, transition" },
    { name: "Temperance", meaning: "Balance, moderation, patience, purpose, meaning" },
    { name: "The Devil", meaning: "Bondage, addiction, sexuality, materialism, playfulness" },
    { name: "The Tower", meaning: "Sudden change, upheaval, chaos, revelation, awakening" },
    { name: "The Star", meaning: "Hope, faith, purpose, renewal, spirituality" },
    { name: "The Moon", meaning: "Illusion, fear, anxiety, subconscious, intuition" },
    { name: "The Sun", meaning: "Positivity, fun, warmth, success, vitality" },
    { name: "Judgement", meaning: "Judgement, rebirth, inner calling, absolution" },
    { name: "The World", meaning: "Completion, accomplishment, travel, fulfillment" }
  ],
  minorArcana: {
    wands: [
      { name: "Ace of Wands", meaning: "Inspiration, ideas, determination, a spark of an inner fire" },
      { name: "Two of Wands", meaning: "Future planning, progress, decisions, discovery" },
      { name: "Three of Wands", meaning: "Progress, expansion, foresight, overseas opportunities" },
      { name: "Four of Wands", meaning: "Celebration, joy, harmony, relaxation, homecoming" },
      { name: "Five of Wands", meaning: "Conflict, disagreements, competition, tension, diversity" },
      { name: "Six of Wands", meaning: "Success, public recognition, progress, self-confidence" },
      { name: "Seven of Wands", meaning: "Challenge, competition, perseverance, defense, maintaining control" },
      { name: "Eight of Wands", meaning: "Speed, action, alignment, air travel, swift change" },
      { name: "Nine of Wands", meaning: "Resilience, courage, persistence, test of faith, boundaries" },
      { name: "Ten of Wands", meaning: "Burden, extra responsibility, hard work, completion, carrying a load" },
      { name: "Page of Wands", meaning: "Inspiration, ideas, discovery, limitless potential, free spirit" },
      { name: "Knight of Wands", meaning: "Energy, passion, inspired action, adventure, impulsiveness" },
      { name: "Queen of Wands", meaning: "Courage, confidence, independence, social butterfly, determination" },
      { name: "King of Wands", meaning: "Natural-born leader, vision, entrepreneur, honour" }
    ],
    cups: [
      { name: "Ace of Cups", meaning: "Love, new relationships, compassion, creativity, overwhelming emotion" },
      { name: "Two of Cups", meaning: "Unified love, partnership, mutual attraction, relationships" },
      { name: "Three of Cups", meaning: "Celebration, friendship, creativity, community, gatherings" },
      { name: "Four of Cups", meaning: "Meditation, contemplation, apathy, reevaluation, discontent" },
      { name: "Five of Cups", meaning: "Regret, failure, disappointment, pessimism, emotional loss" },
      { name: "Six of Cups", meaning: "Revisiting the past, childhood memories, innocence, joy, healing" },
      { name: "Seven of Cups", meaning: "Opportunities, choices, wishful thinking, illusion, dreams" },
      { name: "Eight of Cups", meaning: "Disappointment, abandonment, withdrawal, escapism, searching for meaning" },
      { name: "Nine of Cups", meaning: "Contentment, satisfaction, gratitude, wish come true, happiness" },
      { name: "Ten of Cups", meaning: "Divine love, blissful relationships, harmony, alignment, happiness" },
      { name: "Page of Cups", meaning: "Creative opportunities, intuitive messages, curiosity, possibility" },
      { name: "Knight of Cups", meaning: "Creativity, romance, bringing or receiving a message, imagination" },
      { name: "Queen of Cups", meaning: "Compassionate, caring, emotionally stable, intuitive, in flow" },
      { name: "King of Cups", meaning: "Emotionally balanced, compassionate, diplomatic, giving, spiritually aware" }
    ],
    swords: [
      { name: "Ace of Swords", meaning: "Breakthroughs, new ideas, mental clarity, success, opportunities" },
      { name: "Two of Swords", meaning: "Difficult decisions, weighing up options, an impasse, avoidance" },
      { name: "Three of Swords", meaning: "Heartbreak, emotional pain, sorrow, grief, hurt, separation" },
      { name: "Four of Swords", meaning: "Rest, relaxation, meditation, contemplation, recuperation" },
      { name: "Five of Swords", meaning: "Conflict, disagreements, competition, defeat, winning at all costs" },
      { name: "Six of Swords", meaning: "Transition, change, rite of passage, releasing baggage, journey" },
      { name: "Seven of Swords", meaning: "Betrayal, deception, getting away with something, stealth, sneakiness" },
      { name: "Eight of Swords", meaning: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality" },
      { name: "Nine of Swords", meaning: "Anxiety, worry, fear, depression, nightmares, trauma" },
      { name: "Ten of Swords", meaning: "Painful endings, deep wounds, betrayal, loss, crisis, defeat" },
      { name: "Page of Swords", meaning: "New ideas, curiosity, thirst for knowledge, new ways of communicating" },
      { name: "Knight of Swords", meaning: "Ambitious, action-oriented, driven to succeed, fast-thinking" },
      { name: "Queen of Swords", meaning: "Independent, unbiased judgement, clear boundaries, direct communication" },
      { name: "King of Swords", meaning: "Mental clarity, intellectual power, authority, truth, rational" }
    ],
    pentacles: [
      { name: "Ace of Pentacles", meaning: "A new financial or career opportunity, manifestation, abundance" },
      { name: "Two of Pentacles", meaning: "Multiple priorities, time management, prioritisation, organisation" },
      { name: "Three of Pentacles", meaning: "Collaboration, learning, implementation, teamwork, planning" },
      { name: "Four of Pentacles", meaning: "Saving money, security, conservatism, scarcity, control" },
      { name: "Five of Pentacles", meaning: "Financial loss, poverty, lack mindset, isolation, worry" },
      { name: "Six of Pentacles", meaning: "Giving, receiving, sharing wealth, generosity, charity, gratitude" },
      { name: "Seven of Pentacles", meaning: "Long-term view, sustainable results, perseverance, investment" },
      { name: "Eight of Pentacles", meaning: "Apprenticeship, repetitive tasks, mastery, skill development, craftmanship" },
      { name: "Nine of Pentacles", meaning: "Abundance, luxury, self-sufficiency, financial independence, property" },
      { name: "Ten of Pentacles", meaning: "Wealth, financial security, family, long-term success, contribution" },
      { name: "Page of Pentacles", meaning: "Learning, studying, apprenticeship, new ideas, curiosity" },
      { name: "Knight of Pentacles", meaning: "Hard work, productivity, routine, conservatism, methodical" },
      { name: "Queen of Pentacles", meaning: "Nurturing, practical, providing financially and emotionally, intuitive" },
      { name: "King of Pentacles", meaning: "Financial success, business acumen, security, discipline, abundance" }
    ]
  }
};

module.exports = tarotCards;